name: ainfra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_database: ^11.3.5
  firebase_storage: ^12.4.5
  firebase_messaging: 15.2.5
  cloud_firestore: ^5.6.7

  # Flutter plugins
  flutter_tts: ^4.2.2
  flutter_naver_map: ^1.3.1
  geolocator: ^14.0.0
  permission_handler: ^11.3.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  #cloud_firestore: ^4.13.0
  #speech_to_text: ^6.3.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/sos_button.png

dependency_overrides:
  firebase_auth_platform_interface: ^7.0.3

