name: maptest
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  #여기서부터 추가한 코드
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5
  firebase_messaging: 15.2.5
  cloud_firestore: ^5.6.7

  # Flutter plugins
  flutter_tts: ^4.2.2
  flutter_naver_map: ^1.3.1
  geolocator: ^14.0.0
  geocoding : ^2.1.0
  permission_handler: ^11.3.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  url_launcher: ^6.2.5
  #cloud_firestore: ^4.13.0
  speech_to_text: ^7.0.0
  http: ^1.1.0
  provider: 6.1.1
  dotenv: ^4.1.0
  webview_flutter: ^4.0.0
  webview_flutter_android: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sos_button.png
    - assets/tmap_webview.html


dependency_overrides:
  firebase_auth_platform_interface: ^7.0.3

