name: ainfra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5
  firebase_messaging: 15.2.5
  cloud_firestore: ^5.6.7

  # Flutter plugins
  flutter_tts: ^4.2.2
  flutter_naver_map: ^1.1.2
  geolocator: ^14.0.0
  geocoding : ^2.1.0
  permission_handler: ^11.3.0
  image_picker: ^1.0.4
  url_launcher: ^6.2.5
  #cloud_firestore: ^4.13.0
  speech_to_text: ^6.6.2
  http: ^0.13.6
  provider: 6.1.1
  flutter_map: ^0.14.0 #지도 테스트
  intl: ^0.18.1
  latlong2: ^0.8.0

  # speech_to_text:
  #   path: plugins/speech_to_text
  # audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/sos_button.png

dependency_overrides:
  firebase_auth_platform_interface: ^7.0.3
  intl: ^0.18.1